import React from "react";
import {
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    ScrollView,
    Dimensions,
} from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { MaterialCommunityIcons, Feather, Ionicons } from "@expo/vector-icons";
import Animated, { FadeInDown } from "react-native-reanimated";

const { width } = Dimensions.get("window");

const QUIZ_TOPICS = [
    { id: 1, title: "Espresso Science", count: "12 Qs", color: ["#F59E0B", "#D97706"], icon: "coffee" },
    { id: 2, title: "Milk Texturing", count: "8 Qs", color: ["#3B82F6", "#2563EB"], icon: "water" },
    { id: 3, title: "Customer Service", count: "15 Qs", color: ["#10B981", "#059669"], icon: "account-heart" },
    { id: 4, title: "Machine Maint.", count: "10 Qs", color: ["#6366F1", "#4F46E5"], icon: "cogs" },
];

export default function QuizSection() {
    return (
        <ScrollView
            contentContainerStyle={{ paddingBottom: 100, paddingTop: 20 }}
            showsVerticalScrollIndicator={false}
        >

            {/* DAILY AI CHALLENGE HEADER */}
            <Animated.View entering={FadeInDown.delay(100).duration(600)} style={styles.heroContainer}>
                <LinearGradient
                    colors={["#7C3AED", "#4F46E5"]} // Violet Indigo
                    start={{ x: 0, y: 0 }}
                    end={{ x: 1, y: 1 }}
                    style={styles.heroCard}
                >
                    <View style={styles.heroContent}>
                        <View style={styles.badgeContainer}>
                            <MaterialCommunityIcons name="robot" size={20} color="#FBBF24" />
                            <Text style={styles.badgeText}>DAILY AI CHALLENGE</Text>
                        </View>
                        <Text style={styles.heroTitle}>Beat the AI Logic</Text>
                        <Text style={styles.heroSubtitle}>Answer 5 tricky scenario questions generated by our AI based on your weak spots.</Text>

                        <TouchableOpacity style={styles.startBtn}>
                            <Text style={styles.startBtnText}>Start Challenge</Text>
                            <Feather name="arrow-right" size={20} color="#4F46E5" />
                        </TouchableOpacity>
                    </View>
                    {/* DECORATIVE ILLUST */}
                    <View style={styles.heroDecor}>
                        <MaterialCommunityIcons name="brain" size={120} color="rgba(255,255,255,0.1)" />
                    </View>
                </LinearGradient>
            </Animated.View>

            {/* STREAK & STATS */}
            <View style={styles.statsRow}>
                <View style={styles.statItem}>
                    <MaterialCommunityIcons name="fire" size={24} color="#EF4444" />
                    <View>
                        <Text style={styles.statVal}>12</Text>
                        <Text style={styles.statLabel}>Streak</Text>
                    </View>
                </View>
                <View style={styles.statDivider} />
                <View style={styles.statItem}>
                    <MaterialCommunityIcons name="target" size={24} color="#F59E0B" />
                    <View>
                        <Text style={styles.statVal}>94%</Text>
                        <Text style={styles.statLabel}>Accuracy</Text>
                    </View>
                </View>
            </View>

            {/* TOPICS GRID */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Topic Quizzes</Text>
                <View style={styles.grid}>
                    {QUIZ_TOPICS.map((topic, index) => (
                        <Animated.View
                            key={topic.id}
                            entering={FadeInDown.delay(200 + index * 100).duration(500)}
                            style={styles.topicCardWrapper}
                        >
                            <TouchableOpacity style={[styles.topicCard]}>
                                <LinearGradient
                                    colors={topic.color}
                                    style={styles.topicIconBox}
                                >
                                    <MaterialCommunityIcons name={topic.icon} size={32} color="#FFF" />
                                </LinearGradient>
                                <Text style={styles.topicTitle}>{topic.title}</Text>
                                <Text style={styles.topicCount}>{topic.count}</Text>

                                {/* 3D BOTTOM EDGE */}
                                <View style={styles.cardEdge} />
                            </TouchableOpacity>
                        </Animated.View>
                    ))}
                </View>
            </View>

            {/* COMPLETED QUIZZES */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Recent AI Feedback</Text>
                <View style={styles.feedbackCard}>
                    <View style={styles.feedbackHeader}>
                        <View style={styles.scoreCircle}>
                            <Text style={styles.scoreText}>8/10</Text>
                        </View>
                        <View style={{ flex: 1, marginLeft: 12 }}>
                            <Text style={styles.feedbackTitle}>Espresso Basics</Text>
                            <Text style={styles.feedbackDate}>Yesterday</Text>
                        </View>
                        <TouchableOpacity style={styles.reviewBtn}>
                            <Text style={styles.reviewText}>Review</Text>
                        </TouchableOpacity>
                    </View>
                    <View style={styles.aiCommentBox}>
                        <MaterialCommunityIcons name="robot-happy-outline" size={20} color="#8B5CF6" />
                        <Text style={styles.aiComment}>
                            "Great job! You mastered the extraction timing, but check your tamping pressure consistency next time."
                        </Text>
                    </View>
                </View>
            </View>

        </ScrollView>
    );
}

const styles = StyleSheet.create({
    // HERO
    heroContainer: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    heroCard: {
        borderRadius: 24,
        padding: 24,
        position: 'relative',
        overflow: 'hidden',
    },
    heroContent: {
        zIndex: 10,
    },
    badgeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: "rgba(255,255,255,0.2)",
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        marginBottom: 16,
    },
    badgeText: {
        color: "#FBBF24",
        fontSize: 12,
        fontFamily: "Poppins_700Bold",
        marginLeft: 6,
    },
    heroTitle: {
        fontSize: 28,
        fontFamily: "Poppins_700Bold",
        color: "#FFF",
        marginBottom: 8,
    },
    heroSubtitle: {
        fontSize: 14,
        color: "rgba(255,255,255,0.9)",
        lineHeight: 22,
        marginBottom: 24,
        fontFamily: "Poppins_400Regular",
    },
    startBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: "#FFF",
        alignSelf: 'flex-start',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
    },
    startBtnText: {
        color: "#4F46E5",
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
        marginRight: 8,
    },
    heroDecor: {
        position: 'absolute',
        right: -20,
        bottom: -20,
        zIndex: 1,
    },

    // STATS
    statsRow: {
        flexDirection: 'row',
        backgroundColor: "#FFF",
        marginHorizontal: 20,
        padding: 16,
        borderRadius: 16,
        justifyContent: 'space-evenly',
        alignItems: 'center',
        marginBottom: 30,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    statItem: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '40%',
        justifyContent: 'center',
    },
    statDivider: {
        width: 1,
        height: 30,
        backgroundColor: "#F3F4F6",
    },
    statVal: {
        fontSize: 20,
        fontFamily: "Poppins_700Bold",
        color: "#111827",
        marginLeft: 10,
    },
    statLabel: {
        fontSize: 11,
        color: "#6B7280",
        fontFamily: "Poppins_500Medium",
        marginLeft: 10,
    },

    // TOPICS
    section: {
        paddingHorizontal: 20,
        marginBottom: 30,
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
        color: "#111827",
        marginBottom: 16,
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    topicCardWrapper: {
        width: '48%',
        marginBottom: 16,
    },
    topicCard: {
        backgroundColor: "#FFF",
        borderRadius: 20,
        padding: 16,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: "#F3F4F6",
        borderBottomWidth: 4, // 3D effect
        borderBottomColor: "#E5E7EB",
    },
    topicIconBox: {
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    topicTitle: {
        fontSize: 15,
        fontFamily: "Poppins_600SemiBold",
        color: "#111827",
        marginBottom: 4,
    },
    topicCount: {
        fontSize: 12,
        color: "#9CA3AF",
        fontFamily: "Poppins_500Medium",
    },

    // FEEDBACK
    feedbackCard: {
        backgroundColor: "#FFF",
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: "#F3F4F6",
    },
    feedbackHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    scoreCircle: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "#ECFDF5",
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: "#10B981",
    },
    scoreText: {
        color: "#10B981",
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
    },
    feedbackTitle: {
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
        color: "#111827",
    },
    feedbackDate: {
        fontSize: 12,
        color: "#9CA3AF",
    },
    reviewBtn: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: "#EFF6FF",
        borderRadius: 8,
    },
    reviewText: {
        color: "#3B82F6",
        fontSize: 12,
        fontFamily: "Poppins_600SemiBold",
    },
    aiCommentBox: {
        backgroundColor: "#F5F3FF", // plain violet-50
        padding: 12,
        borderRadius: 12,
        flexDirection: 'row',
    },
    aiComment: {
        flex: 1,
        fontSize: 13,
        fontFamily: "Poppins_400Italic",
        color: "#5B21B6",
        marginLeft: 10,
        fontStyle: 'italic',
    },
});
